description: >-
  Sample community config
user:
  RUN_ENVIR: community
  MACHINE: hera
  ACCOUNT: an_account
platform:
  MODEL: FV3_GFS_v16_CONUS_25km
  MET_INSTALL_DIR: path/to/MET
  METPLUS_PATH: path/to/METPlus
  CCPA_OBS_DIR: /path/to/processed/CCPA/data
  MRMS_OBS_DIR: /path/to/processed/MRMS/data
  NDAS_OBS_DIR: /path/to/processed/NDAS/data
workflow:
  EXPT_SUBDIR: test_community
  DATE_FIRST_CYCL: '20190615'
  DATE_LAST_CYCL: '20190615'
  CYCL_HRS:
  - '00'
  FCST_LEN_HRS: '48'
  PREEXISTING_DIR_METHOD: rename
  VERBOSE: 'TRUE'
  COMPILER: intel
workflow_switches:
  RUN_TASK_MAKE_GRID: 'TRUE'
  RUN_TASK_MAKE_OROG: 'TRUE'
  RUN_TASK_MAKE_SFC_CLIMO: 'TRUE'
  RUN_TASK_GET_OBS_CCPA: 'FALSE'
  RUN_TASK_GET_OBS_MRMS: 'FALSE'
  RUN_TASK_GET_OBS_NDAS: 'FALSE'
  RUN_TASK_VX_GRIDSTAT: 'FALSE'
  RUN_TASK_VX_POINTSTAT: 'FALSE'
  RUN_TASK_VX_ENSGRID: 'FALSE'
  RUN_TASK_VX_ENSPOINT: 'FALSE'
task_run_fcst:
  WTIME_RUN_FCST: 01:00:00
  QUILTING: 'TRUE'
  PREDEF_GRID_NAME: RRFS_CONUS_25km
task_run_get_extrn_ics:
  EXTRN_MDL_NAME_ICS: FV3GFS
  FV3GFS_FILE_FMT_ICS: grib2
task_run_get_extrn_lbcs:
  EXTRN_MDL_NAME_LBCS: FV3GFS
  LBC_SPEC_INTVL_HRS: '6'
  FV3GFS_FILE_FMT_LBCS: grib2
task_run_make_ics:
  CCPP_PHYS_SUITE: FV3_GFS_v16
global:
  DO_ENSEMBLE: 'FALSE'
  NUM_ENS_MEMBERS: '2'
